import type { Database } from "./types"

// Seed data for the SkinLink platform. Two tenant organizations demonstrate
// isolation. All timestamps are ISO strings so the client can format them.

const now = Date.now()
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString()
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString()
const daysAhead = (d: number) => new Date(now + d * 86_400_000).toISOString()

export const seed: Database = {
  tenants: [
    {
      id: "t_mwanza",
      name: "Mwanza Regional Health Network",
      slug: "mwanza-health",
      plan: "growth",
      status: "active",
      country: "Tanzania",
      region: "Mwanza",
      contactName: "Dr. Amina Hassan",
      contactEmail: "amina@mwanzahealth.org",
      seats: 25,
      usedSeats: 14,
      clinics: 8,
      createdAt: daysAgo(210),
      primaryColor: "#1f7a8c",
    },
    {
      id: "t_mtwara",
      name: "Mtwara Coastal Clinics",
      slug: "mtwara-coastal",
      plan: "pilot",
      status: "trial",
      country: "Tanzania",
      region: "Mtwara",
      contactName: "Joseph Mbwana",
      contactEmail: "joseph@mtwaracoastal.org",
      seats: 10,
      usedSeats: 4,
      clinics: 3,
      createdAt: daysAgo(38),
      primaryColor: "#0c6b58",
    },
    {
      id: "t_arusha",
      name: "Arusha Highland Dermatology",
      slug: "arusha-derm",
      plan: "enterprise",
      status: "active",
      country: "Tanzania",
      region: "Arusha",
      contactName: "Dr. Grace Kimaro",
      contactEmail: "grace@arushaderm.org",
      seats: 60,
      usedSeats: 41,
      clinics: 19,
      createdAt: daysAgo(420),
      primaryColor: "#2b4c7e",
    },
  ],

  users: [
    // Platform operator (SkinLink SaaS)
    {
      id: "u_platform",
      tenantId: null,
      name: "SkinLink Operator",
      email: "ops@skinlink.io",
      role: "platform_admin",
      title: "Platform Administrator",
      status: "active",
      avatarColor: "#0c2340",
      lastActive: hoursAgo(1),
      createdAt: daysAgo(500),
    },
    // Mwanza tenant
    {
      id: "u_amina",
      tenantId: "t_mwanza",
      name: "Dr. Amina Hassan",
      email: "amina@mwanzahealth.org",
      role: "org_admin",
      title: "Lead Dermatologist",
      specialty: "General Dermatology",
      phone: "+255 754 100 100",
      status: "active",
      avatarColor: "#1f7a8c",
      lastActive: hoursAgo(2),
      createdAt: daysAgo(210),
    },
    {
      id: "u_daniel",
      tenantId: "t_mwanza",
      name: "Dr. Daniel Okoth",
      email: "daniel@mwanzahealth.org",
      role: "specialist",
      title: "Dermatologist",
      specialty: "Pediatric Dermatology",
      phone: "+255 754 100 101",
      status: "active",
      avatarColor: "#2b4c7e",
      lastActive: hoursAgo(5),
      createdAt: daysAgo(180),
    },
    {
      id: "u_neema",
      tenantId: "t_mwanza",
      name: "Neema Joseph",
      email: "neema@mwanzahealth.org",
      role: "clinician",
      title: "Community Health Worker",
      phone: "+255 754 100 102",
      status: "active",
      avatarColor: "#0c6b58",
      lastActive: hoursAgo(9),
      createdAt: daysAgo(150),
    },
    {
      id: "u_fikiri",
      tenantId: "t_mwanza",
      name: "Fikiri Salum",
      email: "fikiri@mwanzahealth.org",
      role: "clinician",
      title: "Clinic Nurse",
      phone: "+255 754 100 103",
      status: "invited",
      avatarColor: "#8a5a2b",
      lastActive: daysAgo(3),
      createdAt: daysAgo(20),
    },
    // Mtwara tenant
    {
      id: "u_joseph",
      tenantId: "t_mtwara",
      name: "Joseph Mbwana",
      email: "joseph@mtwaracoastal.org",
      role: "org_admin",
      title: "Clinic Coordinator",
      phone: "+255 767 200 200",
      status: "active",
      avatarColor: "#0c6b58",
      lastActive: hoursAgo(20),
      createdAt: daysAgo(38),
    },
    {
      id: "u_halima",
      tenantId: "t_mtwara",
      name: "Dr. Halima Said",
      email: "halima@mtwaracoastal.org",
      role: "specialist",
      title: "Consultant Dermatologist",
      specialty: "General Dermatology",
      phone: "+255 767 200 201",
      status: "active",
      avatarColor: "#1f7a8c",
      lastActive: hoursAgo(30),
      createdAt: daysAgo(30),
    },
    // Arusha tenant
    {
      id: "u_grace",
      tenantId: "t_arusha",
      name: "Dr. Grace Kimaro",
      email: "grace@arushaderm.org",
      role: "org_admin",
      title: "Head of Dermatology",
      specialty: "Surgical Dermatology",
      status: "active",
      avatarColor: "#2b4c7e",
      lastActive: hoursAgo(4),
      createdAt: daysAgo(420),
    },
  ],

  patients: [
    {
      id: "p_fatuma",
      tenantId: "t_mwanza",
      code: "PT-0001",
      fullName: "Fatuma K.",
      age: 45,
      gender: "Female",
      phone: "+255 712 000 001",
      village: "Mbuyuni",
      region: "Mwanza",
      consentObtained: true,
      registeredById: "u_neema",
      createdAt: daysAgo(4),
      notes: "Recurrent itchy patches on forearm.",
    },
    {
      id: "p_juma",
      tenantId: "t_mwanza",
      code: "PT-0002",
      fullName: "Juma A.",
      age: 33,
      gender: "Male",
      phone: "+255 712 000 002",
      village: "Nyakato",
      region: "Mwanza",
      consentObtained: true,
      registeredById: "u_neema",
      createdAt: daysAgo(6),
    },
    {
      id: "p_neemas",
      tenantId: "t_mwanza",
      code: "PT-0003",
      fullName: "Neema S.",
      age: 28,
      gender: "Female",
      village: "Igoma",
      region: "Mwanza",
      consentObtained: true,
      registeredById: "u_fikiri",
      createdAt: daysAgo(7),
    },
    {
      id: "p_peter",
      tenantId: "t_mwanza",
      code: "PT-0004",
      fullName: "Peter M.",
      age: 52,
      gender: "Male",
      phone: "+255 712 000 004",
      village: "Buhongwa",
      region: "Mwanza",
      consentObtained: true,
      registeredById: "u_neema",
      createdAt: daysAgo(9),
      notes: "History of chronic dermatitis.",
    },
    {
      id: "p_asha",
      tenantId: "t_mtwara",
      code: "PT-0001",
      fullName: "Asha M.",
      age: 61,
      gender: "Female",
      village: "Mikindani",
      region: "Mtwara",
      consentObtained: true,
      registeredById: "u_joseph",
      createdAt: daysAgo(2),
    },
  ],

  cases: [
    {
      id: "c_0891",
      tenantId: "t_mwanza",
      ref: "REF-2024-0891",
      patientId: "p_fatuma",
      clinicianId: "u_neema",
      specialistId: "u_amina",
      primaryConcern: "Itchy rash on forearm",
      clinicalInfo: "Itchy rash on forearm, present for 2 days. No fever. Patient reports worsening at night.",
      durationDays: 2,
      suspectedCondition: "Suspected Eczema",
      status: "new",
      priority: "routine",
      images: [
        {
          id: "img_1",
          url: "/dermatology-forearm-rash-eczema-close-up.png",
          angle: "Close-up",
          quality: "good",
          qualityScore: 92,
          capturedAt: hoursAgo(2),
        },
        {
          id: "img_2",
          url: "/skin-lesion-medical-photo-arm.png",
          angle: "Wide",
          quality: "good",
          qualityScore: 88,
          capturedAt: hoursAgo(2),
        },
        {
          id: "img_3",
          url: "/dermatology-skin-condition-macro.png",
          angle: "Macro",
          quality: "acceptable",
          qualityScore: 74,
          qualityNotes: "Slight motion blur",
          capturedAt: hoursAgo(2),
        },
      ],
      ai: {
        imageQualityAverage: 85,
        imageQualityFlags: ["1 image has mild motion blur"],
        differentials: [
          {
            condition: "Atopic Dermatitis",
            confidence: "High",
            probability: 78,
            rationale: "Symmetric, itchy, ill-defined erythematous patches consistent with atopic pattern.",
          },
          {
            condition: "Allergic Contact Dermatitis",
            confidence: "Moderate",
            probability: 54,
            rationale: "Localized distribution could indicate contact allergen exposure.",
          },
          {
            condition: "Psoriasis (plaque)",
            confidence: "Low",
            probability: 21,
            rationale: "Lacks well-demarcated silvery scale typical of plaque psoriasis.",
          },
        ],
        recommendedAction: "Suitable for teledermatology management. Recommend topical corticosteroid trial and review.",
        urgencyFlag: "routine",
        generatedAt: hoursAgo(2),
        model: "skinlink-derm-vision-1",
      },
      notes: [],
      createdAt: hoursAgo(2),
      updatedAt: hoursAgo(2),
    },
    {
      id: "c_0892",
      tenantId: "t_mwanza",
      ref: "REF-2024-0892",
      patientId: "p_juma",
      clinicianId: "u_neema",
      specialistId: "u_daniel",
      primaryConcern: "Rash on forearm",
      clinicalInfo: "Spreading rash on forearm over 4 days, mild burning sensation.",
      durationDays: 4,
      suspectedCondition: "Contact dermatitis",
      status: "in_review",
      priority: "routine",
      images: [
        {
          id: "img_4",
          url: "/skin-rash-dermatitis-forearm-clinical.png",
          angle: "Close-up",
          quality: "good",
          qualityScore: 90,
          capturedAt: hoursAgo(4),
        },
      ],
      notes: [
        {
          id: "n_1",
          authorId: "u_daniel",
          authorName: "Dr. Daniel Okoth",
          body: "Reviewing distribution pattern, likely irritant contact. Awaiting one more image.",
          createdAt: hoursAgo(3),
        },
      ],
      createdAt: hoursAgo(4),
      updatedAt: hoursAgo(3),
    },
    {
      id: "c_0893",
      tenantId: "t_mwanza",
      ref: "REF-2024-0893",
      patientId: "p_neemas",
      clinicianId: "u_fikiri",
      specialistId: "u_amina",
      primaryConcern: "Facial acne",
      clinicalInfo: "Inflammatory acne on cheeks and jawline, 3 weeks. No prior treatment.",
      durationDays: 21,
      suspectedCondition: "Acne / Inflammatory",
      status: "new",
      priority: "routine",
      images: [
        {
          id: "img_5",
          url: "/facial-acne-inflammatory-clinical-dermatology.png",
          angle: "Frontal",
          quality: "good",
          qualityScore: 86,
          capturedAt: hoursAgo(5),
        },
      ],
      notes: [],
      createdAt: hoursAgo(5),
      updatedAt: hoursAgo(5),
    },
    {
      id: "c_0894",
      tenantId: "t_mwanza",
      ref: "REF-2024-0894",
      patientId: "p_peter",
      clinicianId: "u_neema",
      specialistId: "u_daniel",
      primaryConcern: "Chronic dermatitis flare",
      clinicalInfo: "Chronic dermatitis flare on lower legs, ongoing 6 weeks with lichenification.",
      durationDays: 42,
      suspectedCondition: "Chronic dermatitis",
      status: "in_review",
      priority: "urgent",
      images: [
        {
          id: "img_6",
          url: "/chronic-dermatitis-leg-lichenification-clinical.png",
          angle: "Wide",
          quality: "acceptable",
          qualityScore: 71,
          qualityNotes: "Underexposed",
          capturedAt: hoursAgo(6),
        },
      ],
      notes: [],
      createdAt: hoursAgo(6),
      updatedAt: hoursAgo(6),
    },
    {
      id: "c_0890",
      tenantId: "t_mwanza",
      ref: "REF-2024-0890",
      patientId: "p_fatuma",
      clinicianId: "u_neema",
      specialistId: "u_amina",
      primaryConcern: "Follow-up eczema",
      clinicalInfo: "Follow-up of treated eczema, assessing response to topical steroid.",
      durationDays: 14,
      suspectedCondition: "Atopic Dermatitis",
      status: "reviewed",
      priority: "routine",
      images: [
        {
          id: "img_7",
          url: "/healing-eczema-skin-improvement-clinical.png",
          angle: "Close-up",
          quality: "good",
          qualityScore: 89,
          capturedAt: daysAgo(2),
        },
      ],
      treatmentPlan: {
        id: "tp_1",
        diagnosis: "Atopic Dermatitis",
        medications: [
          { name: "Topical corticosteroid", instructions: "Mometasone 0.1% cream, bd for 7-14 days" },
          { name: "Moisturizer", instructions: "Emollient cream, 2-3x daily" },
        ],
        patientEducation: ["Skin care and trigger avoidance advice", "Apply emollient after bathing"],
        avoidTriggers: ["Fragrances", "Harsh soaps", "Scratching"],
        followUpDays: 14,
        notes: "Review progress and adjust treatment.",
        createdById: "u_amina",
        createdAt: daysAgo(2),
      },
      notes: [
        {
          id: "n_2",
          authorId: "u_amina",
          authorName: "Dr. Amina Hassan",
          body: "Good response, continue emollients and taper steroid.",
          createdAt: daysAgo(2),
        },
      ],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
    },
    {
      id: "c_m001",
      tenantId: "t_mtwara",
      ref: "REF-2024-0102",
      patientId: "p_asha",
      clinicianId: "u_joseph",
      specialistId: "u_halima",
      primaryConcern: "Pigmented lesion",
      clinicalInfo: "Irregular pigmented lesion on back, patient unsure of duration.",
      durationDays: 90,
      suspectedCondition: "Pigmented lesion — rule out melanoma",
      status: "new",
      priority: "urgent",
      images: [
        {
          id: "img_8",
          url: "/pigmented-skin-lesion-mole-dermoscopy-clinical.png",
          angle: "Dermoscopy",
          quality: "good",
          qualityScore: 94,
          capturedAt: hoursAgo(20),
        },
      ],
      notes: [],
      createdAt: hoursAgo(20),
      updatedAt: hoursAgo(20),
    },
  ],

  referrals: [
    {
      id: "r_1",
      tenantId: "t_mwanza",
      ref: "REF-2024-0891",
      caseId: "c_0891",
      patientName: "Fatuma K.",
      fromClinic: "Mbuyuni Village Clinic",
      toSpecialistId: "u_amina",
      status: "pending",
      priority: "routine",
      createdAt: hoursAgo(2),
    },
    {
      id: "r_2",
      tenantId: "t_mwanza",
      ref: "REF-2024-0892",
      caseId: "c_0892",
      patientName: "Juma A.",
      fromClinic: "Nyakato Health Post",
      toSpecialistId: "u_daniel",
      status: "accepted",
      priority: "routine",
      createdAt: hoursAgo(4),
    },
    {
      id: "r_3",
      tenantId: "t_mwanza",
      ref: "REF-2024-0890",
      caseId: "c_0890",
      patientName: "Fatuma K.",
      fromClinic: "Mbuyuni Village Clinic",
      toSpecialistId: "u_amina",
      status: "responded",
      priority: "routine",
      createdAt: daysAgo(3),
      respondedAt: daysAgo(2),
    },
    {
      id: "r_m1",
      tenantId: "t_mtwara",
      ref: "REF-2024-0102",
      caseId: "c_m001",
      patientName: "Asha M.",
      fromClinic: "Mikindani Dispensary",
      toSpecialistId: "u_halima",
      status: "pending",
      priority: "urgent",
      createdAt: hoursAgo(20),
    },
  ],

  followUps: [
    {
      id: "f_1",
      tenantId: "t_mwanza",
      caseId: "c_0890",
      caseRef: "REF-2024-0890",
      patientName: "Fatuma K.",
      scheduledFor: daysAhead(12),
      status: "scheduled",
      assignedToId: "u_amina",
      purpose: "Review progress & adjust treatment",
    },
    {
      id: "f_2",
      tenantId: "t_mwanza",
      caseId: "c_0892",
      caseRef: "REF-2024-0892",
      patientName: "Juma A.",
      scheduledFor: daysAgo(1),
      status: "overdue",
      assignedToId: "u_daniel",
      purpose: "Assess treatment response",
    },
    {
      id: "f_3",
      tenantId: "t_mwanza",
      caseId: "c_0893",
      caseRef: "REF-2024-0893",
      patientName: "Neema S.",
      scheduledFor: daysAhead(0),
      status: "due",
      assignedToId: "u_amina",
      purpose: "Acne treatment check-in",
    },
    {
      id: "f_m1",
      tenantId: "t_mtwara",
      caseId: "c_m001",
      caseRef: "REF-2024-0102",
      patientName: "Asha M.",
      scheduledFor: daysAhead(3),
      status: "scheduled",
      assignedToId: "u_halima",
      purpose: "Biopsy result discussion",
    },
  ],

  resources: [
    {
      id: "res_1",
      tenantId: "t_mwanza",
      title: "Eczema care guide",
      category: "Patient Education",
      type: "PDF",
      description: "Printable patient handout for atopic dermatitis care and trigger avoidance.",
      updatedAt: daysAgo(30),
    },
    {
      id: "res_2",
      tenantId: "t_mwanza",
      title: "Image capture best practices",
      category: "Clinical Protocol",
      type: "Protocol",
      description: "How to take clear, well-lit lesion photos from multiple angles.",
      updatedAt: daysAgo(60),
    },
    {
      id: "res_3",
      tenantId: "t_mwanza",
      title: "Teledermatology triage criteria",
      category: "Clinical Protocol",
      type: "Article",
      description: "Guidance on which cases are suitable for remote management vs referral.",
      updatedAt: daysAgo(15),
    },
    {
      id: "res_m1",
      tenantId: "t_mtwara",
      title: "Melanoma red flags (ABCDE)",
      category: "Clinical Protocol",
      type: "PDF",
      description: "Reference for identifying suspicious pigmented lesions.",
      updatedAt: daysAgo(10),
    },
  ],
}
